# Generated by Django 4.0.4 on 2022-04-22 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgPol', models.CharField(max_length=600)),
                ('imgPart', models.CharField(max_length=600)),
                ('imgUF', models.CharField(max_length=600)),
                ('siglaPart', models.CharField(max_length=10)),
                ('nomeCand', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('twitter', models.CharField(max_length=200)),
            ],
        ),
    ]
